### ISSUE TITLE
Add VoxelMap support

### ISSUE THREAD

**Issue by HerosteveFeed** [funniray/minimap-control#1]
It would be very nice if VoxelMap support were added.
Is this possible?

**Comment by funniray** [comment]
I can probably add proper support for this in the future, however, for now you can send players a message containing these values on login

disable cavemaps: `§3 §6 §3 §6 §3 §6 §d`
disable radar: `§3 §6 §3 §6 §3 §6 §e`

(VoxelMap-Updated only)
enable cavemap: `§3 §6 §3 §6 §3 §6 §f`
enable radar: `§3 §6 §3 §6 §3 §6 §0`

**Comment by funniray** [comment]
Supported added in [v1.5.0](https://modrinth.com/plugin/minimap-control/version/1.5.0)
