### ISSUE TITLE
How Xaeros Minimap works

### ISSUE THREAD

**Issue by blue-pinapple** [funniray/minimap-control#3]
Sorry, this isn't exactly an issue, I didn't know where to put this.
I'm unable to get the Plugin because I'm using Aternos
I was wondering if I could disable the radar on Xaeros Minimap without needing this plugin. I just wanted to ask you because you probably know how it works.

Thanks

**Comment by funniray** [comment]
From Xaero's Minimap's curseforge page. Additional see [this issue](https://github.com/funniray/minimap-control/issues/1) for VoxelMap 

## How do I prohibit the use of cave mode and/or entity radar on my server?

To do that, please install the mod on the server side (requires a Forge/Fabric/Quilt server as of writing this). When you start your server, a new "common" config file will be created directly in the server directory (not the world folder). In the config file, you get multiple options that let you disable certain mod features for your players. Changes require a server restart.

Alternatively, you can include the following strings in a server/system message sent to players (on login), which do the following:

`§f§a§i§r§x§a§e§r§o` - causes the minimap to disable cave mode (including world map) and entity radar (fair-play mode)

`§x§a§e§r§o§w§m§n§e§t§h§e§r§i§s§f§a§I§r` - causes world map cave mode to work in the nether despite the minimap being fair-play

`§n§o§m§i§n§i§m§a§p` - disables the minimap completely

`§r§e§s§e§t§x§a§e§r§o` - reset all the system message flags
