### ISSUE TITLE
JourneyMap 1.21-6.0.0

### ISSUE THREAD

**Issue by mysticdrew** [funniray/minimap-control#4]
Hey there, JourneyMap dev here. 
Thanks for this plugin, you saved me from writing it :)  I recommend it often.
I want to let you know as of 6.0.0 for 1.21 only the WorldId packet has the leading 0 byte , I am still supporting the old forge discriminator for that packet. It has been removed from all other packets as I no longer user forge's `SimpleNetwork` for forge packets, I have switched to using 
https://github.com/mysticdrew/common-networking/tree/1.21 which uses `EventNetworkChannel`

**Comment by funniray** [comment]
Hey there, thanks for the heads up! I think I got it all working with the new version 😄 

While you're here, is there any chance that the teleport packet could send the relevant WorldId? Getting minecraft:the_overworld isn't very helpful on a bukkit server 😅 

Also, as a sidenote, you don't seem to be able to see waypoints from different worldids?

If you want, I can open an issue on journeymap instead

**Comment by mysticdrew** [comment]
Nice, thanks! 
So, I plan to rework how map data gets saved eventually. To better handle users changing the name of the server in the multiplayer menu and better folder structures.

When you get a new worldId it treats it as a completely different server. Right now we don't have a way to know if a worldId is a completely different server of the same server with multiple worlds. I do have some plans in the works to change that with the data saving rewrite. 

There will likely be more server options added during the 6.0.0-beta. I would like to say I can remind you when that happens, and I will try but I may forget. 

I saw your edit as I was typing this, only each "server" has a worldId, primarily used for bungeecord style servers or for users that name all their servers in the multiplayer menu the default "Minecraft Server" the worldId keeps that unique.

**Comment by funniray** [comment]
wasn't worldid needed in old versions of bukkit servers before each "bukkit world" had it's own dimension id? iirc old versions gave all worlds the same version id and it would appear like everything was just the overworld (unsure what version would've changed this though)

**Comment by mysticdrew** [comment]
I'm honestly not sure. We've always had the worldid for bungeecord servers.

**Comment by funniray** [comment]
So, I did test and a 1.21 client connecting to a 1.12 based bukkit server using viaversion doesn't get sent different dimension ids and the map will get corrupted (unless a worldid or similar technique is used)
![image](https://github.com/funniray/minimap-control/assets/16416198/507735a3-6058-4bb1-8cc3-63adf81a9461)

I do know at least 1.16 bukkit servers and above do send a proper dimension id for other worlds, however people in the bukkit community unfortunately tend to run older versions of minecraft

**Comment by mysticdrew** [comment]
that is unfortunate. 
I wonder if that is because they don't even try to map the old int dimensionIds to the resource location used to identify dimensions? Or do they send the int to the client and the client fails to map it?

That was changed from `int` to `ResourceLocation` in 1.13 or 1.14
Bukkit 1.12.2 sends the correct dimension ids to 1.12.2 clients

**Comment by mysticdrew** [comment]
Is this server a public server, I can connect to?

**Comment by funniray** [comment]
> Is this server a public server, I can connect to in the future?

It was just a test server I ran locally. Just downloaded paper 1.12.2, ViaVersion and Multiverse. Unfortunately I don't have a good way to make any of my test services publicly accessible rn
