### ISSUE TITLE
Kicked from server with DecoderException after joining with Xaero's Minimap

### ISSUE THREAD

**Issue by Tisawesomeness** [funniray/minimap-control#5]
`io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:custom_payload (class_2658) was larger than I expected, found 20 bytes extra whilst reading packet clientbound/minecraft:custom_payload`
Full error: https://mclo.gs/gvyip82

Running MinimapControl 1.6.0 on Paper `1.21-57-master@0e02aa5`, default config, no other plugins

Mods:
- Xaero's Minimap 24.2.1
- Mod Menu
- Placeholder API
- Fabric API

**Comment by funniray** [comment]
Should be fixed as of v1.8.0!
