### ISSUE TITLE
JourneyMap Data being seperated per dimension

### ISSUE THREAD

**Issue by SpokenWig620933** [funniray/minimap-control#7]
Whenever I try to switch dimensions my journeymap data is recreated in a new folder, version 1.8.0

**Comment by funniray** [comment]
Bukkit is problematic as there's no "root" world folder for me to store the
World's UUID in. I could generate a random UUID that's static per server
which would still solve issues with proxies.

I already have code to detect client versions on bukkit servers, so I'll
probably stick with the current solution for 1.12 and below clients (as
bukkit sends the same dimension id for different worlds prior to 1.13).

**Comment by funniray** [comment]
[1.9.0](https://github.com/funniray/minimap-control/releases/tag/v1.9.0) of the plugin resolved this.
