### ISSUE TITLE
Cannot use the paper under bungee

### ISSUE THREAD

**Issue by Ti-Avanti** [funniray/minimap-control#8]
When I use the paper server under BC, when I switch servers, I will be kicked out by the server and told to use the journeymap mod version 5.8.1 or higher, but I am using the latest version, 5.10.2, and it still gives me this prompt, and I can't use it normally

**Comment by funniray** [comment]
the plugin needs to be installed on all servers or else there can be some weird behaviors on velocity and bungeecord. (see more at TeamJM/journeymap#783)

There were also issues with the version number I had set previously, but that should be resolved as of v1.11.0 of the plugin
